project:
  type: website
  output-dir: docs

website:
  title: "maryana balezina"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual


