---
title: "Current research"
format: 
  html:
    toc: true
    self-contained: true
editor: source
author: Maryana Balezina
theme: flatly
execute: 
  cache: true
  warning: false
  message: false
  fig-width: 12 
  fig-height: 9
---

## Including trans* athletes: it's not only about prejudice

I am currently working on **sport policies** and **trans\* discrimination**. The idea for this research came from a hunch that maybe with some sporting competition, people get agitated about trans* inclusionary policies more often, than in other sports. For example, one would probably not be against inclusion of trans* athletes into a charity race where participant pay a little fee to enter the competition and the money go to a charity; but, if at the end of the race the winner gets all the money, some might show reservation towards trans* inclusion, especially when it comes to trans* women competing against cis women. Following this intuition led me to learning a lot of random facts about sporting competitions, but also to a realization that even people who have negative attitudes towards trans* individuals might still show some support for trans* inclusionary policies under certain conditions.

After 2024 Olympics I conducted a survey experiment in the US, where I asked participants to share their opinion on a proposed policy that regulates participation of trans* athletes. The results somewhat supported my intuition. I am working on the paper draft right now and hopefully will be able to talk about the results more openly at a later point. 

## Fair and/but discriminatory? The role of percieved discrimination in policy support

Another intuition that I had about trans* athletes was that maybe people see some policies as discriminatory, but justifiably discriminatory. For example, one can argue that discriminating against trans* women in sport is required to keep the competition fair. It is wrong to exclude, but under certain conditions it is fair and necessary. This seems somewhat counterintuitive, considering that usually folk call unfair behavior discriminatory (or discriminatory behavior unfair), which indicates that the concepts of discrimination and fairness are tightly connected. But in the hypothetical argument given, it feels like people talk about a different kind of fairness. What do people mean, then, when they say a policy is fair or discriminatory? And does it affect whether people are supportive of a policy?

I'm still thinking about these question and have yet to find certain answers. I plan to answer these concerns by focusing on sports ethics and discrimination theory literature, as I believe those field can more precisely reflect the meaning behind big concepts like "fairness" in sports. Though, at the end of the day, I enjoy asking folk people and having empirical data, so this is going to be more of an x-phi paper on the relationship between the two concepts in lay people.  